<?xml version="1.0" encoding="utf-8"?><Database Name="DB_9FC383_musiceducation" Class="ApplicationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=hana\SQLEXPRESS;Initial Catalog=DB_9FC383_musiceducation;Integrated Security=True" SettingsObjectName="MusicEducation.Service.Properties.Settings" SettingsPropertyName="DB_9FC383_musiceducationConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Answer" Member="Answers">
    <Type Name="Answer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsValid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Answer_Question_Answer" Member="Question_Answers" ThisKey="Id" OtherKey="Id_Answer" Type="Question_Answer" />
      <Association Name="Answer_User_Question_Answer" Member="User_Question_Answers" ThisKey="Id" OtherKey="Id_Answer" Type="User_Question_Answer" />
    </Type>
  </Table>
  <Table Name="dbo.User_User" Member="User_Users">
    <Type Name="User_User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_UserBoss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserSubordinate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_User_User" Member="User" ThisKey="Id_UserBoss" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_User_User1" Member="User1" ThisKey="Id_UserSubordinate" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MessageType" Member="MessageTypes">
    <Type Name="MessageType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="MessageType_User_Message" Member="User_Messages" ThisKey="Id" OtherKey="Message_Type" Type="User_Message" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_QuestionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Question_Question_Answer" Member="Question_Answers" ThisKey="Id" OtherKey="Id_Question" Type="Question_Answer" />
      <Association Name="Question_Test_Question" Member="Test_Questions" ThisKey="Id" OtherKey="Id_Question" Type="Test_Question" />
      <Association Name="Question_User_Question_Answer" Member="User_Question_Answers" ThisKey="Id" OtherKey="Id_Question" Type="User_Question_Answer" />
      <Association Name="QuestionType_Question" Member="QuestionType" ThisKey="Id_QuestionType" OtherKey="Id" Type="QuestionType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Question_Answer" Member="Question_Answers">
    <Type Name="Question_Answer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Answer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Answer_Question_Answer" Member="Answer" ThisKey="Id_Answer" OtherKey="Id" Type="Answer" IsForeignKey="true" />
      <Association Name="Question_Question_Answer" Member="Question" ThisKey="Id_Question" OtherKey="Id" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionType" Member="QuestionTypes">
    <Type Name="QuestionType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="QuestionType_Question" Member="Questions" ThisKey="Id" OtherKey="Id_QuestionType" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Role_Role_RoleProperty" Member="Role_RoleProperties" ThisKey="Id" OtherKey="Id_Role" Type="Role_RoleProperty" />
      <Association Name="Role_User_Role" Member="User_Roles" ThisKey="Id" OtherKey="Id_Role" Type="User_Role" />
    </Type>
  </Table>
  <Table Name="dbo.Role_RoleProperty" Member="Role_RoleProperties">
    <Type Name="Role_RoleProperty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_RoleProperty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Role_Role_RoleProperty" Member="Role" ThisKey="Id_Role" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="RoleProperty_Role_RoleProperty" Member="RoleProperty" ThisKey="Id_RoleProperty" OtherKey="Id" Type="RoleProperty" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RoleProperty" Member="RoleProperties">
    <Type Name="RoleProperty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="RoleProperty_Role_RoleProperty" Member="Role_RoleProperties" ThisKey="Id" OtherKey="Id_RoleProperty" Type="Role_RoleProperty" />
    </Type>
  </Table>
  <Table Name="dbo.Test" Member="Tests">
    <Type Name="Test">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Complexity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_TestType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Test_Test_Question" Member="Test_Questions" ThisKey="Id" OtherKey="Id_Test" Type="Test_Question" />
      <Association Name="Test_User_Question_Answer" Member="User_Question_Answers" ThisKey="Id" OtherKey="Id_Test" Type="User_Question_Answer" />
      <Association Name="Test_User_Test" Member="User_Tests" ThisKey="Id" OtherKey="Id_Test" Type="User_Test" />
      <Association Name="TestType_Test" Member="TestType" ThisKey="Id_TestType" OtherKey="Id" Type="TestType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Test_Question" Member="Test_Questions">
    <Type Name="Test_Question">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Test" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Question_Test_Question" Member="Question" ThisKey="Id_Question" OtherKey="Id" Type="Question" IsForeignKey="true" />
      <Association Name="Test_Test_Question" Member="Test" ThisKey="Id_Test" OtherKey="Id" Type="Test" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestType" Member="TestTypes">
    <Type Name="TestType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="TestType_Test" Member="Tests" ThisKey="Id" OtherKey="Id_TestType" Type="Test" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="DateBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserBase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_User_User" Member="User_Users" ThisKey="Id" OtherKey="Id_UserBoss" Type="User_User" />
      <Association Name="User_User_User1" Member="User_Users1" ThisKey="Id" OtherKey="Id_UserSubordinate" Type="User_User" />
      <Association Name="User_User" Member="Users" ThisKey="Id" OtherKey="Id_UserBase" Type="User" />
      <Association Name="User_User_Message" Member="User_Messages" ThisKey="Id" OtherKey="Id_UserFrom" Type="User_Message" />
      <Association Name="User_User_Message1" Member="User_Messages1" ThisKey="Id" OtherKey="Id_UserTo" Type="User_Message" />
      <Association Name="User_User_Message2" Member="User_Messages2" ThisKey="Id" OtherKey="Id_UserCreate" Type="User_Message" />
      <Association Name="User_User_Message3" Member="User_Messages3" ThisKey="Id" OtherKey="Id_UserDelete" Type="User_Message" />
      <Association Name="User_User_Notification" Member="User_Notifications" ThisKey="Id" OtherKey="Id_User" Type="User_Notification" />
      <Association Name="User_User_Question_Answer" Member="User_Question_Answers" ThisKey="Id" OtherKey="Id_User" Type="User_Question_Answer" />
      <Association Name="User_User_Role" Member="User_Roles" ThisKey="Id" OtherKey="Id_User" Type="User_Role" />
      <Association Name="User_User_Test" Member="User_Tests" ThisKey="Id" OtherKey="Id_User" Type="User_Test" />
      <Association Name="User_User" Member="User1" ThisKey="Id_UserBase" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User_Message" Member="User_Messages">
    <Type Name="User_Message">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_UserFrom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message_Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Message_Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Message_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MessageType_User_Message" Member="MessageType" ThisKey="Message_Type" OtherKey="Id" Type="MessageType" IsForeignKey="true" />
      <Association Name="User_User_Message" Member="User" ThisKey="Id_UserFrom" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_User_Message1" Member="User1" ThisKey="Id_UserTo" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_User_Message2" Member="User2" ThisKey="Id_UserCreate" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_User_Message3" Member="User3" ThisKey="Id_UserDelete" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User_Notification" Member="User_Notifications">
    <Type Name="User_Notification">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PriorityLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_User_Notification" Member="User" ThisKey="Id_User" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User_Question_Answer" Member="User_Question_Answers">
    <Type Name="User_Question_Answer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_Test" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Answer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Result" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Answer_User_Question_Answer" Member="Answer" ThisKey="Id_Answer" OtherKey="Id" Type="Answer" IsForeignKey="true" />
      <Association Name="Question_User_Question_Answer" Member="Question" ThisKey="Id_Question" OtherKey="Id" Type="Question" IsForeignKey="true" />
      <Association Name="Test_User_Question_Answer" Member="Test" ThisKey="Id_Test" OtherKey="Id" Type="Test" IsForeignKey="true" />
      <Association Name="User_User_Question_Answer" Member="User" ThisKey="Id_User" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User_Role" Member="User_Roles">
    <Type Name="User_Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_User_Role" Member="User" ThisKey="Id_User" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Role_User_Role" Member="Role" ThisKey="Id_Role" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User_Test" Member="User_Tests">
    <Type Name="User_Test">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Test" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ValidAnswers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValidPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Test_User_Test" Member="Test" ThisKey="Id_Test" OtherKey="Id" Type="Test" IsForeignKey="true" />
      <Association Name="User_User_Test" Member="User" ThisKey="Id_User" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetAvalibleTests" Method="GetAvalibleTests">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAvalibleTestsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Complexity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateUser_Test_Custom" Method="UpdateUser_Test_Custom">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <Parameter Name="test_name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="test_complexity" Type="System.Int32" DbType="Int" />
    <Parameter Name="test_id_TestType" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetRoles" Method="GetRoles">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRolesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStudents" Method="GetStudents">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetStudentsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTests" Method="GetTests">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTestsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Complexity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestType_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestType_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="CountAnswerValid" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="CountUserAnswerValid" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="UserAnswerValidPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_User_Test" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="allCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountAttempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTestsForStudent" Method="GetTestsForStudent">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTestsForStudentResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Complexity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestType_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestType_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="CountAnswerValid" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="CountUserAnswerValid" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="UserAnswerValidPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="allCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountAttempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUser" Method="GetUser">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(64)" />
    <ElementType Name="GetUserResult">
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="AllCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AvgValidAnswers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AvgValidPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserById" Method="GetUserById">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetUserByIdResult">
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="AllCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AvgValidAnswers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AvgValidPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserRoles" Method="GetUserRoles">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(64)" />
    <ElementType Name="GetUserRolesResult">
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUsers" Method="GetUsers">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetUsersResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Creator_LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Creator_FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Creator_MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DateBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertQuestion_Answer" Method="InsertQuestion_Answer">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idQuestion" Type="System.Int32" DbType="Int" />
    <Parameter Name="answer_name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="answer_content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="answer_isValid" Type="System.Int32" DbType="Int" />
    <ElementType Name="InsertQuestion_AnswerResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertTest_Question" Method="InsertTest_Question">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <Parameter Name="question_name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="question_content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="question_type" Type="System.Int32" DbType="Int" />
    <ElementType Name="InsertTest_QuestionResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertTestWithContent" Method="InsertTestWithContent">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="test_name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="test_complexity" Type="System.Int32" DbType="Int" />
    <Parameter Name="question_name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="question_content" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertUser" Method="InsertUser">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="dateCreate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="lastName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="firstName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="middleName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(512)" />
    <Parameter Name="roleName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="InsertUserResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUser_Question_Answer" Method="InsertUser_Question_Answer">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <Parameter Name="idQuestion" Type="System.Int32" DbType="Int" />
    <Parameter Name="idAnswer" Type="System.Int32" DbType="Int" />
    <Parameter Name="answer_content" Type="System.String" DbType="Text" />
    <ElementType Name="InsertUser_Question_AnswerResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Complexity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Result" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CountAnswerValid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountUserAnswerValid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserAnswerValidPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUser_Test" Method="InsertUser_Test">
    <Parameter Name="idMainUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <Parameter Name="idUserTestType" Type="System.Int32" DbType="Int" />
    <Parameter Name="countAttempts" Type="System.Int32" DbType="Int" />
    <Parameter Name="isShowHints" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="InsertUser_TestResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUser_Test_Custom" Method="InsertUser_Test_Custom">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <Parameter Name="test_name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="test_complexity" Type="System.Int32" DbType="Int" />
    <Parameter Name="test_id_TestType" Type="System.Int32" DbType="Int" />
    <ElementType Name="InsertUser_Test_CustomResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateQuestion_Answer" Method="UpdateQuestion_Answer">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idQuestion" Type="System.Int32" DbType="Int" />
    <Parameter Name="idAnswer" Type="System.Int32" DbType="Int" />
    <Parameter Name="answer_name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="answer_content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="answer_isValid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateTest_Question" Method="UpdateTest_Question">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idQuestion" Type="System.Int32" DbType="Int" />
    <Parameter Name="question_name" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="question_content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="question_type" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateUser" Method="UpdateUser">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="dateCreate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="idUserCore" Type="System.Int32" DbType="Int" />
    <Parameter Name="lastName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="firstName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="middleName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(512)" />
    <Parameter Name="roleName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="UpdateUserResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateUser_Test" Method="UpdateUser_Test">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <Parameter Name="validAnswers" Type="System.Int32" DbType="Int" />
    <Parameter Name="validPercent" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTest" Method="GetTest">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTestResult">
      <Column Name="Id_Test" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Test_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Question_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Question_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Question_Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Question_QuestionType_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Answer_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Answer_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Answer_Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CountAttempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsShowHints" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_User_TestType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsValid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>