<?xml version="1.0" encoding="utf-8"?><Database Name="DB_9FC383_musiceducation" Class="ApplicationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SQL5031.myASP.NET;Initial Catalog=DB_9FC383_musiceducation;Persist Security Info=True;User ID=DB_9FC383_musiceducation_admin" SettingsObjectName="MusicEducation.Service.Properties.Settings" SettingsPropertyName="DB_9FC383_musiceducationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Answer" Member="Answers">
    <Type Name="Answer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsValid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Answer_Question_Answer" Member="Question_Answers" ThisKey="Id" OtherKey="Id_Answer" Type="Question_Answer" />
      <Association Name="Answer_User_Question_Answer" Member="User_Question_Answers" ThisKey="Id" OtherKey="Id_Answer" Type="User_Question_Answer" />
    </Type>
  </Table>
  <Table Name="dbo.User_Role" Member="User_Roles">
    <Type Name="User_Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_User_Role" Member="User" ThisKey="Id_User" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Question_Question_Answer" Member="Question_Answers" ThisKey="Id" OtherKey="Id_Question" Type="Question_Answer" />
      <Association Name="Question_Test_Question" Member="Test_Questions" ThisKey="Id" OtherKey="Id_Question" Type="Test_Question" />
      <Association Name="Question_User_Question_Answer" Member="User_Question_Answers" ThisKey="Id" OtherKey="Id_Question" Type="User_Question_Answer" />
    </Type>
  </Table>
  <Table Name="dbo.Question_Answer" Member="Question_Answers">
    <Type Name="Question_Answer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Answer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Answer_Question_Answer" Member="Answer" ThisKey="Id_Answer" OtherKey="Id" Type="Answer" IsForeignKey="true" />
      <Association Name="Question_Question_Answer" Member="Question" ThisKey="Id_Question" OtherKey="Id" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Role_Role_RoleProperty" Member="Role_RoleProperties" ThisKey="Id" OtherKey="Id_Role" Type="Role_RoleProperty" />
    </Type>
  </Table>
  <Table Name="dbo.Role_RoleProperty" Member="Role_RoleProperties">
    <Type Name="Role_RoleProperty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_RoleProperty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Role_Role_RoleProperty" Member="Role" ThisKey="Id_Role" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="RoleProperty_Role_RoleProperty" Member="RoleProperty" ThisKey="Id_RoleProperty" OtherKey="Id" Type="RoleProperty" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RoleProperty" Member="RoleProperties">
    <Type Name="RoleProperty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="RoleProperty_Role_RoleProperty" Member="Role_RoleProperties" ThisKey="Id" OtherKey="Id_RoleProperty" Type="Role_RoleProperty" />
    </Type>
  </Table>
  <Table Name="dbo.Test" Member="Tests">
    <Type Name="Test">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Complexity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Test_Test_Question" Member="Test_Questions" ThisKey="Id" OtherKey="Id_Test" Type="Test_Question" />
      <Association Name="Test_User_Question_Answer" Member="User_Question_Answers" ThisKey="Id" OtherKey="Id_Test" Type="User_Question_Answer" />
    </Type>
  </Table>
  <Table Name="dbo.Test_Question" Member="Test_Questions">
    <Type Name="Test_Question">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Test" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Question_Test_Question" Member="Question" ThisKey="Id_Question" OtherKey="Id" Type="Question" IsForeignKey="true" />
      <Association Name="Test_Test_Question" Member="Test" ThisKey="Id_Test" OtherKey="Id" Type="Test" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_User_Role" Member="User_Roles" ThisKey="Id" OtherKey="Id_User" Type="User_Role" />
      <Association Name="User_User_Question_Answer" Member="User_Question_Answers" ThisKey="Id" OtherKey="Id_User" Type="User_Question_Answer" />
    </Type>
  </Table>
  <Table Name="dbo.User_Question_Answer" Member="User_Question_Answers">
    <Type Name="User_Question_Answer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_UserDelete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateDelete" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_Test" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Answer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Result" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Answer_User_Question_Answer" Member="Answer" ThisKey="Id_Answer" OtherKey="Id" Type="Answer" IsForeignKey="true" />
      <Association Name="Question_User_Question_Answer" Member="Question" ThisKey="Id_Question" OtherKey="Id" Type="Question" IsForeignKey="true" />
      <Association Name="Test_User_Question_Answer" Member="Test" ThisKey="Id_Test" OtherKey="Id" Type="Test" IsForeignKey="true" />
      <Association Name="User_User_Question_Answer" Member="User" ThisKey="Id_User" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.InsertUser" Method="InsertUser">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="dateCreate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="lastName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="firstName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="middleName" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(64)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(512)" />
    <ElementType Name="InsertUserResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserRoles" Method="GetUserRoles">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(64)" />
    <ElementType Name="GetUserRolesResult">
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTest" Method="GetTest">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTestResult">
      <Column Name="Id_Test" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Test_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Question_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Question_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Question_Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Answer_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Answer_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Answer_Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTests" Method="GetTests">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetTestsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Complexity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Result" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CountAnswerValid" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="CountUserAnswerValid" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="UserAnswerValidPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUser" Method="GetUser">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="login" Type="System.String" DbType="NVarChar(64)" />
    <ElementType Name="GetUserResult">
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Id_UserCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUser_Question_Answer" Method="InsertUser_Question_Answer">
    <Parameter Name="idUser" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTest" Type="System.Int32" DbType="Int" />
    <Parameter Name="idQuestion" Type="System.Int32" DbType="Int" />
    <Parameter Name="idAnswer" Type="System.Int32" DbType="Int" />
    <ElementType Name="InsertUser_Question_AnswerResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Complexity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Result" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CountAnswerValid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountUserAnswerValid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserAnswerValidPercent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>